on: push
name: Deploy on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Linting and type checking
        run: npm run lint
      - name: Tests
        run: npm run test
      - name: Build project
        run: npm run build
      - name: Upload ftp
        if: github.ref == 'refs/heads/main'
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: niklaskorz.lima-ftp.de
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "apps/example/dist"
          remoteDir: "/"
          forceSsl: true
